/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemUsageRouteImport } from './routes/memUsage'
import { Route as CpuUsageRouteImport } from './routes/cpuUsage'
import { Route as IndexRouteImport } from './routes/index'

const MemUsageRoute = MemUsageRouteImport.update({
  id: '/memUsage',
  path: '/memUsage',
  getParentRoute: () => rootRouteImport,
} as any)
const CpuUsageRoute = CpuUsageRouteImport.update({
  id: '/cpuUsage',
  path: '/cpuUsage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cpuUsage': typeof CpuUsageRoute
  '/memUsage': typeof MemUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cpuUsage': typeof CpuUsageRoute
  '/memUsage': typeof MemUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cpuUsage': typeof CpuUsageRoute
  '/memUsage': typeof MemUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cpuUsage' | '/memUsage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cpuUsage' | '/memUsage'
  id: '__root__' | '/' | '/cpuUsage' | '/memUsage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CpuUsageRoute: typeof CpuUsageRoute
  MemUsageRoute: typeof MemUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memUsage': {
      id: '/memUsage'
      path: '/memUsage'
      fullPath: '/memUsage'
      preLoaderRoute: typeof MemUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpuUsage': {
      id: '/cpuUsage'
      path: '/cpuUsage'
      fullPath: '/cpuUsage'
      preLoaderRoute: typeof CpuUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CpuUsageRoute: CpuUsageRoute,
  MemUsageRoute: MemUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
